---
# vars file for manage_repositories
manage_repositories_default_repo:
  - name: debian
    uri: "{{ manage_repositories_main_repo_uri[ansible_distribution|lower] }}"
    comments: "debian main repository"
    types:
      - deb
    suites:
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_release }}-updates"
      - "{{ ansible_distribution_release }}-backports"
    components:
      - main
  - name: debian-security
    uri: "{{ manage_repositories_main_repo_uri[ansible_distribution|lower] }}-security"
    comments: "debian main repository"
    types:
      - deb
    suites:
      - "{{ ansible_distribution_release }}-security"
    components:
      - main
