---
# task/install file for renew_consul_certificates
- name: "Configure hashicorp repository"
  ansible.builtin.include_role:
    name: ednxzu.manage_repositories
  vars:
    manage_repositories_enable_default_repo: false
    manage_repositories_enable_custom_repo: true
    manage_repositories_custom_repo: "{{ renew_consul_certificates_repository }}"

- name: "Install consul-template"
  ansible.builtin.include_role:
    name: ednxzu.manage_apt_packages
  vars:
    manage_apt_packages_list: "{{ renew_consul_certificates_packages }}"
