---
# defaults file for install_docker
install_docker_edition: ce # can be ce or ee (community or enterprise)
install_docker_auto_update: false
install_docker_start_service: true
install_docker_compose: false
install_docker_compose_version: latest
install_docker_python_packages: false
install_docker_python_packages_version: latest
install_docker_users: []
install_docker_daemon_options: {}
