---
# meta file for hashicorp_nomad
galaxy_info:
  namespace: "ednz_cloud"
  role_name: "hashicorp_nomad"
  author: "Bertrand Lanson"
  description: "Install and configure hashicorp nomad for debian-based distros."
  license: "license (BSD, MIT)"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - "ubuntu"
    - "debian"
    - "hashicorp"
    - "nomad"

dependencies: []
