---
# vars file for renew_consul_certificates
renew_consul_certificates_repository:
  - name: hashicorp
    uri: "https://apt.releases.hashicorp.com"
    comments: "hashicorp repository"
    types:
      - deb
    suites:
      - "{{ ansible_distribution_release }}"
    components:
      - main
    options:
      Signed-By: "https://apt.releases.hashicorp.com/gpg"
renew_consul_certificates_packages:
  - name: consul-template
    version: latest
    state: present
