---
# meta file for docker_systemd_service
galaxy_info:
  namespace: 'ednxzu'
  role_name: 'docker_systemd_service'
  author: 'Bertrand Lanson'
  description: 'Create Systemd services for docker containers.'
  license: 'license (BSD, MIT)'
  min_ansible_version: '2.10'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - 'ubuntu'
    - 'debian'
    - 'docker'
    - 'systemd'

dependencies: []
